# Generated by Django 2.0 on 2018-09-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RenderApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='user',
        ),
    ]
