# Generated by Django 2.0 on 2018-09-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenderApp', '0002_remove_fornecedor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoiadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Apoiador')),
                ('funcao', models.CharField(max_length=200, verbose_name='Função')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='logo-apoiadores', verbose_name='Imagem Destaque')),
            ],
        ),
    ]
