# Generated by Django 2.0 on 2018-09-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RenderApp', '0004_apoiadores_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
